# Generated by Django 3.2.15 on 2023-01-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
