# Generated by Django 4.1.5 on 2023-03-05 22:19

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_tracker_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='duration',
            field=fernet_fields.fields.EncryptedIntegerField(),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='end_date',
            field=fernet_fields.fields.EncryptedDateField(),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='start_date',
            field=fernet_fields.fields.EncryptedDateField(),
        ),
    ]
